### ISSUE TITLE
Relationships with IsingleContainer?

### ISSUE THREAD

**Issue by JimSEOW** [exrin/ExrinQuickStart#1]
For exrin 2.0 beta: Refactored and reduced API complexity.
What are the reduced API complexity? When creating SingleContainer app, no more reference to ISingleContainer?

Or the Reduced API gives user the option of QUICK Start to begin Exrin.

After that Users can assess the more advanced Container concepts?

**Comment by adamped** [comment]
@JimSEOW - The ISingleContainer still exists and is used. What I did here was make it that if a stack, isn't connected to any container, it automatically creates an ISingleContainer and add it in there. For simple one navigation stacks, it means you don't need to both creating the container if you don't want to. But you still can. 

Nothing was taken away, just simplified, but can become more advanced if you choose, you just add it in. This way everyone starts at the simplest option and can move to the advanced if they need to.

**Comment by JimSEOW** [comment]
@adamped   I agree. It draws new user AND this is important for Exrin dissemination.

Still I encourage new users to watch [the introduction to Exrin](https://www.youtube.com/watch?v=VCmetoNpL4M) - to understand the true potential of Exrin, beyond this QuickStart!
