### ISSUE TITLE
Ideal for other Exrin sample - EF Core 2.0

### ISSUE THREAD

**Issue by JimSEOW** [exrin/ExrinQuickStart#2]
As part of your [14 days to Entreprise Xamarin App](http://xamarinhelp.com/14-days-to-building-an-enterprise-quality-xamarin-forms-app)

Perhaps with the release of[ EF Core 2.0](https://blogs.msdn.microsoft.com/dotnet/2017/08/14/announcing-entity-framework-core-2-0/), it is time to bring this to [Day 10 of Local Storage](http://www.xamarinhelp.com/local-storage-day-10/).

**Comment by adamped** [comment]
Yes, I will put that on my list to update.
